version: '3'

services:
  database:
    image: postgres:11.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Abc_1234
    ports:
      - "5432:5432"
    volumes:
      - datavolume:/var/lib/postgresql/data
    networks:
      - production-control-db-network

networks: 
  production-control-db-network:
    driver: bridge

volumes:
  datavolume:
